### ISSUE TITLE
Handle uppercase sequences like a word

### ISSUE THREAD

**Issue by joelmo** [bkad/CamelCaseMotion#15]
Here is a suggestion for improvement in these cases:
```
| | = cursor
UPPERstrin|g|_foo = start position

motion b 2 times results in:
UPPE|R|string_foo
U|P|PERstring_foo

expected:
UPPER|s|tring_foo
|U|PPERstring_foo

---

|U|PPERstr_foo = start

motion e:
UPP|E|R|str_foo

expected:
UPPE|R|str_foo


motion w 2 times:
U|P|PERstr_foo
UPPE|R|str_foo

expected:
UPPER|s|tr_foo
UPPERstr_|f|oo
```

**Comment by bkad** [comment]
I've made an adjustment to the way the plugin behaves for consecutive capital characters in https://github.com/bkad/CamelCaseMotion/commit/54c1932c2a431b31b38473079417ff6d2d9310da, and find the behavior to be correct now. I've modified your example from `UPPERstring_foo` to `UPPERString_foo` to better highlight the corrected behavior:

```
UPPERStrin|g|_foo = start position

motion b 2 times results in:
UPPER|S|tring_foo
|U|PPERString_foo

---

|U|PPERString_foo = start

motion e:
UPPE|R|String_foo

motion w 2 times:
UPPER|S|tring_foo
UPPERString_|f|oo
```
