### ISSUE TITLE
Changing word at the end of a string causes it to delete past the new line

### ISSUE THREAD

**Issue by psylinse** [bkad/CamelCaseMotion#18]
Take a ruby block of code like:

``` ruby
if something
  "This is a sentence."
end
```

If you place your cursor at the `s` in `sentence` and `c,w` it sucks up the `.`, `"` and `\n'. The normal vim behavior is to stop at the`.`.

**Comment by bkad** [comment]
Interesting, mine eats the `."` but not the newline, I can take a look.

**Comment by jetaggart** [comment]
Looks like it's related to #17. I've noticed if I do `c,w` on something like `a_method.another_method` starting on the `m` in `method` it eats the `.` too.

**Comment by petersohn** [comment]
It seems to eat any punctuation characters, and even whitespaces at the end of the words. For example:

     void SomeClass::someMethod() {
    }

If I do `c,w` from `Class`, it eats the `::`, and if I do it from `Method`, it eats until `{` (but leaves the `{` alone).

**Comment by faceleg** [comment]
Does #21 result in more expected behaviour?

**Comment by petersohn** [comment]
That pull request seems to solve the problem, thanks.
