### ISSUE TITLE
support Vundle management

### ISSUE THREAD

**Issue by wolftune** [bkad/CamelCaseMotion#22]
I would really prefer this to work as a regular plugin I can set up with Vundle. Is that possible?

**Comment by AndreasPetersen** [comment]
Just add `Plugin 'bkad/CamelCaseMotion'` to your `.vimrc` and run `:PluginInstall`. I did find that I had to manually add the key bindings.

**Comment by wolftune** [comment]
great, I may have once tried that, but doubted it since the vimball instructions confused me and I missed the idea that the default was `,w` instead of just `w`. In my case, just installing actually worked without manually doing anything with keybinding today. So, this is working. I submitted a PR to improve your README. Cheers
