### ISSUE TITLE
plugin just took over my leader key

### ISSUE THREAD

**Issue by acornejo** [bkad/CamelCaseMotion#26]
I've been using this plugin happily for a while.

A recent update to it took over my leader key and overwrites a lot of mappings I was already using.

The leader key is usually reserved for users customizing VIM, since it is guaranteed not to be taken up by anything else. I preferred the old , behavior, but frankly it would be even better to have a "camelleader" variable that we can set.

PS: I don't think anything is written in stone with the leader key, but I can say that out of the 30+ plugins I have installed right now, this is the only one that decided to map itself to my leader key.

**Comment by bkad** [comment]
I agree, that's pretty shitty default behavior. What if instead it didn't create any mappings by default but required you to call a function like `CamelCaseMotion#CreateMotionMappings('<leader>')` and/or `map <silent> <leader>w <Plug>CamelCaseMotion_w` in your vimrc? I think I would personally prefer that.

**Comment by acornejo** [comment]
Either of your suggestions seems good to me (maybe both?).

An alternative (variation of what I had suggested originally) is:

```
let g:CamelCaseMotionPrefix = 'whatever key or even <leader> if you want'
```

And if that variable is not set (which you can check really easily), then skip all the mappings. If it is set, then set the mappings with the specified prefix key.

**Comment by bkad** [comment]
I decided to resolve it by requiring a call to `camelcasemotion#CreateMotionMappings('<leader>')` to get the current default behavior. Custom mappings worked as they did before.
