### ISSUE TITLE
diw deletes more than it should

### ISSUE THREAD

**Issue by ghostcow** [bkad/CamelCaseMotion#28]
Hello, I installed your package and use the example bindings from the README.

The problem is, when I use 'diw' to delete a word inside a camelcase word (or an underscored word), it deletes more than it should:

```
this_is_an_e[x]ample_here (diw) -> this_is_an_[e]re
thisIsAnE[x]ampleHere (diw) -> thisIsAn[e]re
```

```
[t]his_is_an_example_here (diw) -> [s]_an_esample_here
[t]hisIsAnExampleHere (diw) -> [s]AnExampleHere
```

When it should be:
`[t]his_is_an_example_here (diw) -> _is_an_example_here or is_an_example_here`

**Comment by bkad** [comment]
Yup, can confirm the issue. I'll look into it.

**Comment by bkad** [comment]
Thanks for the fix, @jpassaro!
