### ISSUE TITLE
Alternative plugin

### ISSUE THREAD

**Issue by chaoren** [bkad/CamelCaseMotion#29]
Hi,

I was using this plugin and wanted to fix some of the issues here, but the single giant regex looked like a nightmare to deal with, so I just wrote my own version: https://github.com/chaoren/vim-wordmotion
Note that this is not a fork. I wrote it from scratch.

AFAICT, my implementation has none of the bugs on your issue tracker:
https://github.com/bkad/CamelCaseMotion/issues/28 https://github.com/bkad/CamelCaseMotion/issues/19 https://github.com/bkad/CamelCaseMotion/issues/18 https://github.com/bkad/CamelCaseMotion/issues/17 https://github.com/bkad/CamelCaseMotion/issues/10 https://github.com/bkad/CamelCaseMotion/issues/9

**Comment by bkad** [comment]
Neat, I'll give it a try!

**Comment by deiwin** [comment]
That plugin does not seem to support sub-word text objects, though

**Comment by deiwin** [comment]
Okay, my mistake. It does support sub-word text objects. It's just that the mappings are confusing when configured with a prefix (`,iw` vs the expected `i,w` with the `,` prefix).

As this is getting off topic I'll move my comments over to the other repo.

**Comment by bkad** [comment]
Added this to the list of alternatives in the README.
