### ISSUE TITLE
`<leader>w` cost 3 second to jump to the next word in visual mode

### ISSUE THREAD

**Issue by jinleileiking** [bkad/CamelCaseMotion#30]

**Comment by bkad** [comment]
Not able to reproduce this, can you provide the bindings you're using in your vimrc?

**Comment by jinleileiking** [comment]
https://github.com/jinleileiking/DotFiles/blob/master/.vimrc

**Comment by Asheq** [comment]
I'm guessing this line in your vimrc is the problem:

`map <Leader>wp ve"0p`

Vim is waiting to see if you are going to type the p or not.

**Comment by bkad** [comment]
@Asheq thanks for finding the issue!
