### ISSUE TITLE
Possibly unintended behaviour with Camel Case

### ISSUE THREAD

**Issue by bk2dcradle** [bkad/CamelCaseMotion#31]
Consider I have the following text:

```
ThisSh|o|uldNotWorkLikeThis
```

If I do `ci,w`, I get this:

```
ThisotWorkLikeThis
```

I really think that `N` should not be deleted. In other words, `ci,w` deletes the current camel word and the first letter of the next camel word. Is this the intended behaviour? Because I checked out a few of the previous commits to see if this was unintended, but seems like this has existed for a pretty long time.

**Comment by cstanfill** [comment]
I also ran into this behavior today having just installed this plugin. It seems questionable to me, too (I'd prefer that i,w work as you suggest), but you can workaround by doing ci,e in that case.

**Comment by ninrod** [comment]
I also have this problem. I first ran into this problem at least a year ago.

**Comment by bkad** [comment]
Thanks for the fix, @jpassaro!
