### ISSUE TITLE
ciw doesn't work as expected

### ISSUE THREAD

**Issue by tcchau** [bkad/CamelCaseMotion#44]
![vim-ciw](https://user-images.githubusercontent.com/3226200/116590100-60381080-a8eb-11eb-81ed-63b346bb31af.gif)

I was expecting this command to put me into insert mode right after the 'd' in 'selected'.

**Comment by bkad** [comment]
what mode does it put you into instead?

**Comment by tcchau** [comment]
@bkad Sorry I was in a rush and didn't make it clear. 

I was expecting it to put into insert mode with the cursor right after 'd' in 'selected', and with the rest of the line intact, i.e. delete up to the closing backtick. 

Instead, it's deleting to the end of the line including the newline causing the next line to join onto the current one.

It's not a big deal as I just need to re-type the backtick and semi-colon, but I didn't think this was the intended behaviour.

**Comment by bkad** [comment]
I agree, the behavior is unexpected, especially when compared to the default vim `ciw`. The behavior you're looking for is contained in `CamelCaseMotion_ie`. I have left the current behavior for legacy reasons, but I could see changing it to reduce confusion might be worth it.
