### ISSUE TITLE
CamelCaseMotion_w slow

### ISSUE THREAD

**Issue by michaelmior** [bkad/CamelCaseMotion#45]
I set the default mappings and find that `CamelCaseMotion_b` and `CamelCaseMotion_e` are almost instant. However, `CamelCaseMotion_w` takes over one second. Any idea what could be happening?

Even stranger, `<leader>w` is slow, but `c<leader>w` is not.

**Comment by bkad** [comment]
I haven't heard of this issue before, it would help me a lot if you could provide me details on how to reproduce it.

The fact that `<leader>w` is slow but `c<leader>w` is not leads me to think that there might be something else going on with your environment. Is `CamelCaseMotion_w` slow on a bare minimal setup? Does your full setup exhibit the same behavior on other machines?

**Comment by michaelmior** [comment]
@bkad This is my fault for not doing more debugging on my own first. I have another plugin that uses the mapping `<leader>ww` so presumably vim was waiting to see if I was doing that first. When I disable that other mapping, everything works fine. Sorry to waste your time :)
