### ISSUE TITLE
Cannot make de,db motions work even though ve,vb motions work

### ISSUE THREAD

**Issue by jwav** [bkad/CamelCaseMotion#47]
I run Neovim 0.7.2 and the latest version of CamelCaseMotion.

I'm not sure if my config is the problem, but I've tried a bunch of ones and still cannot solve this problem.
Let's say I have this word and the cursor is represented by `^`:
```
CamelCaseWord
      ^
```
When doing `ve`, `ase` is selected. When doing `vb`,  `Ca` is selected. The `die` and `dib` motion work as well. All good.

However, if i do `de`, `CamelC` remains instead of `CamelCWord

Here's the config I've been using. I've tried most combinations of these blocks and failed all the time: 

```
" let g:camelcasemotion_key = '<leader>'

" tried with and without this block
map <silent> w <Plug>CamelCaseMotion_w
map <silent> b <Plug>CamelCaseMotion_b
map <silent> e <Plug>CamelCaseMotion_e

" tried with and without this block
map w <Plug>CamelCaseMotion_w
map b <Plug>CamelCaseMotion_b
map e <Plug>CamelCaseMotion_e
" map <silent> ge <Plug>CamelCaseMotion_ge
" nnoremap <silent> ce <Plug>CamelCaseMotion_ce

" what does it do already?
" tried with and without this block
sunmap w
sunmap b
sunmap e
" sunmap ge

" TODO : ve, vw, vb work as intended in CamelCase and snake_case. However: de, ce, etc do not

" tried with and without this block
omap <silent> iw <Plug>CamelCaseMotion_iw
xmap <silent> iw <Plug>CamelCaseMotion_iw
omap <silent> ib <Plug>CamelCaseMotion_ib
xmap <silent> ib <Plug>CamelCaseMotion_ib
omap <silent> ie <Plug>CamelCaseMotion_ie
xmap <silent> ie <Plug>CamelCaseMotion_ie

" tried with and without this block
omap <silent> db <Plug>CamelCaseMotion_db
xmap <silent> db <Plug>CamelCaseMotion_db
omap <silent> de <Plug>CamelCaseMotion_de
xmap <silent> de <Plug>CamelCaseMotion_de
```

**Comment by bkad** [comment]
I wasn't able to reproduce this issue, but I was able to find some bugs around mixed ALLCAPS and CamelCase caps words. I usually struggle with issues of user plugins and custom configuration when reproducing bugs, so I made a little repo that you might also find useful in narrowing down the case of your issue: https://github.com/bkad/CamelCaseMotion-Docker

It's just a small repo with a neovim, minimal CamelCaseMotion configuration, and a sample file to test out word motions.

**Comment by jwav** [comment]
Thanks for replying.

I just tested the issue in nvim within the docker env from https://github.com/bkad/CamelCaseMotion-Docker:
The issue doesn't exist within that env, `de` works as expected.

I took the lua from the config file in that env:
```vim.keymap.set('', 'w', '<Plug>CamelCaseMotion_w', { silent = true })
vim.keymap.set('', 'b', '<Plug>CamelCaseMotion_b', { silent = true })
vim.keymap.set('', 'e', '<Plug>CamelCaseMotion_e', { silent = true })
vim.keymap.set('', 'ge', '<Plug>CamelCaseMotion_ge', { silent = true })
```
And loaded it instead of my .vim config, but the problem stayed: the motions `de` and `db` delete several_words, even though the `e` and `b` motions work as intended.

It might be interference from another plugin or config somewhere but I don't think any of them tamper with how `de` works. Plus, the CamelCaseMotion plugin is the last plugin to load, so it should overwrite anything set by other plugins with its `map` calls.
After loading CamelCaseMotion, I'm just setting the theme and background color, which I don't suspect of altering the `de` motion.
 
Any idea ?

**Comment by bkad** [comment]
Check if it persists between different filetypes, sometimes syntax files change up what are considered keyword characters which affects the movement regexs. Failing that, it's probably some other plugin or config somewhere!

**Comment by jwav** [comment]
I just managed to make it work with this config:
```
unmap w
unmap b
unmap e
map w <Plug>CamelCaseMotion_w
map b <Plug>CamelCaseMotion_b
map e <Plug>CamelCaseMotion_e
nmap de de
nmap db db
nmap dw dw
```
It seems that a previous mapping of mine (`nnoremap de "_de`) messed things up for CamelCaseMotion (CCM), but the `nmap de de` line at the end of the above config sorts it out so that `de` now behaves as CCM intended.

However, I now have the problem of `de` yanking the deleted part into the pasting buffer (default Vim behavior, which I very much don't want).
I'm now trying to figure out a way to have `de` behave the CCM way **without** yanking the deleted part, as if using `"_de`.

So far, no success. Do you have an idea on how to get that behavior ?

**Comment by bkad** [comment]
```lua
vim.keymap.set('', 'de', '"_d:<C-U>call camelcasemotion#Motion("e", v:count1, "n")<CR>', { silent = true })
```

**Comment by jwav** [comment]
[SOLVED]
You nailed it. Now I get exactly the behavior I needed.
I ended up using VimScript, here's my config for posterity:
```
" I mapped `de` to `"_dw` because the `e` motion leaves the last letter of the word.
" If that's what you want, put a "e" in the line below instead of "w"
nnoremap de "_d:<C-U>call camelcasemotion#Motion("w", v:count1, "n")<CR>
nnoremap db "_d:<C-U>call camelcasemotion#Motion("b", v:count1, "n")<CR>
nnoremap dw "_d:<C-U>call camelcasemotion#Motion("w", v:count1, "n")<CR>
nnoremap ce "_c:<C-U>call camelcasemotion#Motion("w", v:count1, "n")<CR>
nnoremap cb "_c:<C-U>call camelcasemotion#Motion("b", v:count1, "n")<CR>
nnoremap cw "_c:<C-U>call camelcasemotion#Motion("w", v:count1, "n")<CR>
```
