### ISSUE TITLE
Neovim can't get c/d operators to work

### ISSUE THREAD

**Issue by Integralist** [bkad/CamelCaseMotion#48]
👋🏻 

Apologies, but I'm just not sure how to set up the configuration to get operations/motions such as `ce`, `de`, `ve` (and equivalent for `w`/`b`) to work.

My current Neovim/lua configuration is...

```lua
vim.keymap.set("n", "w", "<Plug>CamelCaseMotion_w", { desc = "camel case motion w" })
vim.keymap.set("n", "b", "<Plug>CamelCaseMotion_b", { desc = "camel case motion b" })
vim.keymap.set("n", "e", "<Plug>CamelCaseMotion_e", { desc = "camel case motion e" })
```

These work fine for movements, but the moment I want to delete/change with `w`/`e`/`b` it doesn't work and I'm not sure what I should configure to get that to work.

I tried adding something like the following which didn't work:

```lua
vim.keymap.set({ "x", "n", "o" }, "iw", "<Plug>CamelCaseMotion_iw", { desc = "camel case motion iw" })
vim.keymap.set({ "x", "n", "o" }, "ib", "<Plug>CamelCaseMotion_ib", { desc = "camel case motion ib" })
vim.keymap.set({ "x", "n", "o" }, "ie", "<Plug>CamelCaseMotion_ie", { desc = "camel case motion ie" })
```

Any help is appreciated. 

Thanks.

**Comment by bkad** [comment]
I wasn't able to reproduce this particular issue. I usually struggle with issues of user plugins and custom configuration when reproducing bugs, so I made a little repo which has helped another user narrow down the specific issue they had with their configuration that you might also find helpful: https://github.com/bkad/CamelCaseMotion-Docker

It's just a small repo with a neovim, minimal CamelCaseMotion configuration, and a sample file to test out word motions.

The last time someone had issues with this working, they had rebound their `d` operator to have to yank into the empty register: https://github.com/bkad/CamelCaseMotion/issues/47#issuecomment-1265181866

**Comment by Integralist** [comment]
Thank you. I'll check this out on Monday and let you know.

**Comment by Integralist** [comment]
Great idea to use a Docker container, although it failed to build for me on an M1 mac 😬 

That said I just copied the config from that repo:

```
vim.keymap.set('', 'w', '<Plug>CamelCaseMotion_w', { silent = true })
vim.keymap.set('', 'b', '<Plug>CamelCaseMotion_b', { silent = true })
vim.keymap.set('', 'e', '<Plug>CamelCaseMotion_e', { silent = true })
vim.keymap.set('', 'ge', '<Plug>CamelCaseMotion_ge', { silent = true })
```

And it worked how I expected it to 👍🏻 🙂 

Thanks!

**Comment by Integralist** [comment]
I think there were two problems:

1. I was setting the mappings for 'normal' mode only (you have an empty string)
2. I didn't set whatever `_ge` is.
